version: '3'

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/redisData/
    
services:
  discord-lookup:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: discord-lookup
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discord-lookup.rule=Host(`discord-lookup.egirl.ing`)"
      - "traefik.http.routers.discord-lookup.entrypoints=http"
      - "traefik.http.routers.discord-lookup.middlewares=discord-lookup-https-redirect"
      - "traefik.http.middlewares.discord-lookup-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.discord-lookup-secure.rule=Host(`discord-lookup.egirl.ing`)"
      - "traefik.http.routers.discord-lookup-secure.entrypoints=https"
      - "traefik.http.routers.discord-lookup-secure.tls=true"
      - "traefik.http.routers.discord-lookup-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.discord-lookup-secure.tls.domains[0].main=discord-lookup.egirl.ing"
      - "traefik.http.routers.discord-lookup-secure.tls.domains[0].sans=*.discord-lookup.egirl.ing"
      - "traefik.http.routers.discord-lookup-secure.service=discord-lookup-node"
      - "traefik.http.services.discord-lookup-node.loadbalancer.server.port=3000"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mainstack_default
    ports:
      - 3000:3000
    environment:
      TZ: Europe/Berlin
    depends_on:
      - redisDB
  redisDB:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass uwumepw
    volumes: 
      - redis_data:/data
    networks:
      - mainstack_default

networks:
  mainstack_default:
    external: true
